[project]
name = "efl-1-to-24s"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flet[all]==0.28.3",
    "pip>=25.1.1",
    "python-dotenv>=1.1.0",
    "supabase>=2.15.2",
]
